/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2021-05-06 06:55:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class js005_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>이벤트 - JQuery</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<input type=\"text\" id=\"txt\" class=\"cls_txt\" name=\"txt\" placeholder=\"입력란...\"/>\r\n");
      out.write("\t\t<input type=\"text\" id=\"txt2\" class=\"cls_txt\" name=\"txt2\" placeholder=\"입력란2...\"/>\r\n");
      out.write("\t\t<input type=\"text\" id=\"txt3\" class=\"cls_txt\" name=\"txt3\" placeholder=\"입력란3...\"/>\r\n");
      out.write("\t\t<input type=\"button\" value=\"입력체크\" onclick=\"fn_check();\"/>\r\n");
      out.write("\t\t<input type=\"button\" value=\"값 출력\" onclick=\"fn_print();\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"contentsArea\">\r\n");
      out.write("\t\t\t콘텐츠 영역입니다.\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<input type=\"button\" value=\"변경\" onclick=\"fn_change();\"/>\r\n");
      out.write("\t\t<input type=\"button\" value=\"추가\" onclick=\"fn_add();\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.6.0.js\" ></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction fn_check() {\r\n");
      out.write("\t\t\t//$('#txt').val(\"testtest!!!\");\r\n");
      out.write("\t\t\t//$('.cls_txt').val(\"클래스 테스트 입니다.\");\t\r\n");
      out.write("\t\t\t//$('input').val(\"태그네임 selector\");\t\r\n");
      out.write("\t\t\t//$('input[name=\"txt\"]').val(\"txt입니다.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//alert($('#txt').attr('type'));\r\n");
      out.write("\t\t\t$('#txt').attr('type', 'button');\r\n");
      out.write("\t\t\t$('#txt').val('입력체크2');\r\n");
      out.write("\t\t\t$('#txt').attr('onclick', 'fn_check2();');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#txt2').attr('onclick', 'fn_check2();');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_check2() {\r\n");
      out.write("\t\t\talert('버튼으로 변경되었습니다.');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_change() {\r\n");
      out.write("\t\t\t$('#contentsArea').html('<a href=\"https://naver.com\">' + $('#contentsArea').html() + '네이버</a>');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_add() {\r\n");
      out.write("\t\t\t$('#contentsArea').append(\"추가된 내용입니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_print() {\r\n");
      out.write("\t\t\tvar cnt = 0;\r\n");
      out.write("\t\t\t$('.cls_txt').each(function() {\r\n");
      out.write("\t\t\t\tif($(this).attr(\"id\") == \"txt3\") {\r\n");
      out.write("\t\t\t\t\talert(\"값이 바꼈네요.\");\r\n");
      out.write("\t\t\t\t\t$(this).attr(\"id\", \"txt4\");\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\tfn_print();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
