/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2021-05-07 01:45:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class js009_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>animation</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"div1\" style=\"width: 100px; height: 100px; background-color: yellow;\"></div>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn1_1\" value=\"hide\"/>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn1_2\" value=\"show\"/>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn1_3\" value=\"toggle\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"div2\" style=\"width: 100px; height: 100px; background-color: red;\"></div>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn2_1\" value=\"fadeOut\"/>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn2_2\" value=\"fadeIn\"/>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn2_3\" value=\"fadeToggle\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"div3\" style=\"width: 100px; height: 100px; background-color: blue;\"></div>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn3_1\" value=\"slideUp\"/>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn3_2\" value=\"slideDown\"/>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn3_3\" value=\"slideToggle\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"div4\" style=\"width: 100px; height: 100px; background-color: green;\"></div>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn4_1\" value=\"fadeTo\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"div5\" style=\"width: 100px; height: 100px; background-color: orange;\"></div>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn5_1\" value=\"시작\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"div6\" style=\"width: 100px; height: 100px; background-color: purple;\"></div>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn6_1\" value=\"늘어남\"/>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn6_2\" value=\"줄어듬\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"div7\" style=\"width: 100px; height: 100px; background-color: pink;\"></div>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn7_1\" value=\"좌\"/>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn7_2\" value=\"우\"/>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn7_3\" value=\"상\"/>\r\n");
      out.write("\t\t<input type=\"button\" id=\"btn7_4\" value=\"하\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$('#btn1_1').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div1').hide(1000); //1000 : 1초 만에 숨김\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btn1_2').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div1').show(2000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btn1_3').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div1').toggle(500);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* fade--- : 서서히 사라지거나 나타남 */\r\n");
      out.write("\t\t$('#btn2_1').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div2').fadeOut();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btn2_2').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div2').fadeIn();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btn2_3').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div2').fadeToggle();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* slide--- : 미끄러지듯 사라지거나 나타남 */\r\n");
      out.write("\t\t$('#btn3_1').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div3').slideUp();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btn3_2').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div3').slideDown();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btn3_3').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div3').slideToggle();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* fadeTo : 어느정도 사라질지 직접 결정 */\r\n");
      out.write("\t\t$('#btn4_1').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div4').fadeTo(1000, 0.5, function() { //time, opacity(투명도), function\r\n");
      out.write("\t\t\t\talert(\"완료되었습니다.\");\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 깜박이게 만듦 */\r\n");
      out.write("\t\t$('#btn5_1').bind('click', function() {\r\n");
      out.write("\t\t\tfn_hide();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_hide() {\r\n");
      out.write("\t\t\t$('#div5').fadeTo(500, 0, function() {\r\n");
      out.write("\t\t\t\tfn_show();\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_show() {\r\n");
      out.write("\t\t\t$('#div5').fadeTo(500, 1, function() {\r\n");
      out.write("\t\t\t\tfn_hide();\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* animate : {css}, time, option, function */\r\n");
      out.write("\t\t$('#btn6_1').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div6').animate({width: '1000px'}, 1000, 'linear', function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btn6_2').bind('click', function() {\r\n");
      out.write("\t\t\t$('#div6').animate({width: '100px'}, 1000, 'linear', function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar marginL = 0;\r\n");
      out.write("\t\t$('#btn7_1').bind('click', function() {\r\n");
      out.write("\t\t\tmarginL = marginL - 100;\r\n");
      out.write("\t\t\t$('#div7').animate({marginLeft: marginL + 'px'}, 100, 'linear', function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btn7_2').bind('click', function() {\r\n");
      out.write("\t\t\tmarginL = marginL + 100;\r\n");
      out.write("\t\t\t$('#div7').animate({marginLeft: marginL + 'px'}, 100, 'linear', function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar marginT = 0;\r\n");
      out.write("\t\t$('#btn7_3').bind('click', function() {\r\n");
      out.write("\t\t\tmarginT = marginT - 100;\r\n");
      out.write("\t\t\t$('#div7').animate({marginTop: marginT + 'px'}, 100, 'linear', function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btn7_4').bind('click', function() {\r\n");
      out.write("\t\t\tmarginT = marginT + 100;\r\n");
      out.write("\t\t\t$('#div7').animate({marginTop: marginT + 'px'}, 100, 'linear', function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
